service: serverless-note-app

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - ${file(src/iam/notes-table-iam.yml):NotesTableIAM}
  environment:
    AUTH0_PUBLIC_KEY: ${file(secret.pem)}
    NOTES_TABLE_NAME: ${self:custom.NotesTable.name}

functions:
  auth:
    handler: src/handlers/private/auth.handler
    # cors: true
  publicEndpoint:
    handler: src/handlers/public/home.handler
    events:
      - http:
          path: public
          method: POST
          cors: true

  createNote:
    handler: src/handlers/private/notes/create-note.handler
    events:
      - http:
          path: /note
          method: POST
          authorizer: auth
          cors: true
  listNotes:
    handler: src/handlers/private/notes/list-notes.handler
    events:
      - http:
          path: /notes
          method: GET
          authorizer: auth
          cors: true
  listNote:
    handler: src/handlers/private/notes/get-single-note.handler
    events:
    - http:
        path: /note/{id}
        method: GET
        authorizer: auth
        cors: true
  updateNote:
    handler: src/handlers/private/notes/update-single-note.handler
    events:
    - http:
        path: /note/{id}
        method: PUT
        authorizer: auth
        cors: true

resources:
  Resources:
    # Reference to the database table...
    NotesTable: ${file(src/resources/notes-table.yml):NotesTable}

    # GatewayResponse:
    #   Type: 'AWS::ApiGateway::GatewayResponse'
    #   Properties:
    #     ResponseParameters:
    #       gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
    #       gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
    #     ResponseType: EXPIRED_TOKEN
    #     RestApiId:
    #       Ref: 'ApiGatewayRestApi'
    #     StatusCode: '401'
    # AuthFailureGatewayResponse:
    #   Type: 'AWS::ApiGateway::GatewayResponse'
    #   Properties:
    #     ResponseParameters:
    #       gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
    #       gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
    #     ResponseType: UNAUTHORIZED
    #     RestApiId:
    #       Ref: 'ApiGatewayRestApi'
    #     StatusCode: '401'
custom:
  bundle:
    linting: false
  NotesTable:
    name: !Ref NotesTable
    arn: !GetAtt NotesTable.Arn
